### ISSUE TITLE
Official site is down

### ISSUE THREAD

**Issue by GenesisFR** [KasumiL5x/Fullscreenizer#2]
Neither http://www.ngreen.org/ nor http://www.dgreen.me/ are working as of writing this. Therefore, there's no download to a compiled executable.

Maybe you could add one on GitHub?

**Comment by KasumiL5x** [comment]
Sorry about that, I let my hosting package expire!

My daily machine is a Mac now, but when I find time between work and whatnot, I'll dust off my Windows laptop and make a build.

**Comment by KasumiL5x** [comment]
Found some time to make a build!

**Comment by GenesisFR** [comment]
Awesome! Gonna update [PCGamingWiki](https://www.pcgamingwiki.com/wiki/Glossary:Borderless_fullscreen_windowed#Fullscreenizer) then.
